# Generated by Django 5.0.4 on 2024-06-08 16:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('massage', models.TextField(verbose_name='پیام')),
                ('name', models.CharField(max_length=150, verbose_name='نام')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(max_length=11, verbose_name='')),
                ('subject', models.CharField(max_length=150, verbose_name='موضوع')),
            ],
            options={
                'verbose_name': 'تیکت ها',
                'verbose_name_plural': 'نظرات و انتقادات',
            },
        ),
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('name', models.CharField(max_length=150, verbose_name='نام')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='اسلاگ')),
                ('status', models.CharField(choices=[('PN', 'در حال آماده سازی'), ('PB', 'منتشر شده'), ('RJ', 'رد صلاحیت')], default='PN', max_length=50, verbose_name='وضعیت')),
                ('inmate', models.CharField(max_length=150, verbose_name='ملیت')),
                ('image', models.ImageField(null=True, upload_to='Home_page', verbose_name='تصویر')),
                ('description', models.TextField(null=True, verbose_name='توضیحات')),
                ('age', models.CharField(max_length=50, verbose_name='سن (سال تولد)')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'نویسنده',
                'verbose_name_plural': 'نویسنده ها و شاعران',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['id'], name='Home_author_id_b5928d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Literature',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ چاپ')),
                ('description', models.TextField(null=True, verbose_name='توضیحات')),
                ('publishers', models.CharField(max_length=150, verbose_name='انتشارات')),
                ('status', models.CharField(choices=[('PN', 'در حال آماده سازی'), ('PB', 'منتشر شده'), ('RJ', 'رد صلاحیت')], default='PN', max_length=50, verbose_name='وضعیت')),
                ('image', models.ImageField(null=True, upload_to='Home_page', verbose_name='تصویر')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='اسلاگ')),
                ('type', models.CharField(choices=[('bk', 'کتاب'), ('jn', 'مجله'), ('ar', 'مقاله')], default='bk', max_length=50, verbose_name='نوع')),
                ('topics', models.CharField(choices=[('NN', 'None'), ('FNL', 'رمان خارجی آمریکا لاتین'), ('FNA', 'رمان خارجی آمریکا شمالی'), ('FNE', 'رمان خارجی انگلستان'), ('FNS', 'رمان خارچی اسپانیا'), ('FNF', 'رمان خارجی فرانسه'), ('FNG', 'رمان خارچی آلمان'), ('FNR', 'رمان خارجی روسیه'), ('SS', 'داستان کوتاه'), ('KT', 'کودک و نوجوان'), ('FA', 'فانتزی'), ('PR', 'جنایی و کارآگاهی'), ('PO', 'سیاسی'), ('RE', 'دینی و مذهبی'), ('SP', 'ورزشی'), ('WO', 'زنان'), ('PM', 'شعر'), ('HIST', 'تاریخی'), ('BG', 'زندگینامه'), ('TR', 'سفرنامه')], default='NN', max_length=50, verbose_name='موضوع')),
                ('publish_post_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار پست')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, max_length=150, null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.authors', verbose_name='نویسنده')),
                ('author_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_posts', to=settings.AUTH_USER_MODEL, verbose_name='سازنده پست')),
            ],
            options={
                'verbose_name': 'پست',
                'verbose_name_plural': 'پست ها',
                'ordering': ['-publish_post_time'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام')),
                ('description', models.TextField(verbose_name='متن')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ تصحیح')),
                ('active', models.BooleanField(default=False, verbose_name='تاییدیه')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='Home.literature', verbose_name='پست')),
            ],
            options={
                'verbose_name': 'کامنت',
                'verbose_name_plural': 'کامنت ها',
                'ordering': ['created'],
            },
        ),
        migrations.AddIndex(
            model_name='literature',
            index=models.Index(fields=['-publish_post_time'], name='Home_litera_publish_924f57_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['created'], name='Home_commen_created_67724f_idx'),
        ),
    ]
