# Generated by Django 5.0.4 on 2024-06-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='شماره تلفن'),
        ),
    ]
