# Generated by Django 5.0.4 on 2024-06-08 21:03

import django.utils.timezone
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_ticket_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authors',
            name='image',
        ),
        migrations.RemoveField(
            model_name='literature',
            name='image',
        ),
        migrations.AlterField(
            model_name='authors',
            name='created',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='authors',
            name='updated',
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ تصحیح'),
        ),
        migrations.AlterField(
            model_name='literature',
            name='created',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='literature',
            name='date',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ چاپ'),
        ),
        migrations.AlterField(
            model_name='literature',
            name='publish_post_time',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار پست'),
        ),
        migrations.AlterField(
            model_name='literature',
            name='updated',
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
    ]
