# Generated by Django 5.0.4 on 2024-06-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_alter_image_image_alter_image_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Author_Images/', verbose_name='تصویر نویسندگان'),
        ),
    ]
